dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

script:
  - cd project/myCrossing
  - npm install
  - npm update
  - npm test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox